In [1]:
import numpy as np
import pickle
import cv2
from os import listdir
from sklearn.preprocessing import LabelBinarizer
from keras.models import Sequential
from tensorflow.keras import models
from keras.layers import BatchNormalization
from keras.layers import Conv2D
from keras.layers import MaxPooling2D, AveragePooling2D
from keras.layers.core import Activation, Flatten, Dropout, Dense
from keras import backend as K
from keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.optimizers import Adam
from keras.preprocessing import image
from tensorflow import keras
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.preprocessing.image import array_to_img,img_to_array,load_img 
from tensorflow.keras.models import Model 
import pandas as pd

2023-02-28 19:46:07.550183: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-28 19:46:07.877398: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/limsim/.local/lib/python3.10/site-packages/cv2/../../lib64:
2023-02-28 19:46:07.877421: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-02-28 19:46:08.852834: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerr

In [2]:
from tensorflow.keras.applications import MobileNet
from tensorflow.keras.applications.mobilenet import preprocess_input

In [3]:
base_model = MobileNet(weights='imagenet')
model = Model(inputs = base_model.input,outputs = base_model.get_layer('reshape_2').output)

2023-02-28 19:46:10.773808: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-02-28 19:46:10.774476: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/limsim/.local/lib/python3.10/site-packages/cv2/../../lib64:
2023-02-28 19:46:10.774565: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/limsim/.local/lib/python3.10/site-packages/cv2/../../lib64:
2023-02-28 19:46:10.774797: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not lo

In [4]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 224, 224, 3)]     0         
                                                                 
 conv1 (Conv2D)              (None, 112, 112, 32)      864       
                                                                 
 conv1_bn (BatchNormalizatio  (None, 112, 112, 32)     128       
 n)                                                              
                                                                 
 conv1_relu (ReLU)           (None, 112, 112, 32)      0         
                                                                 
 conv_dw_1 (DepthwiseConv2D)  (None, 112, 112, 32)     288       
                                                                 
 conv_dw_1_bn (BatchNormaliz  (None, 112, 112, 32)     128       
 ation)                                                      

                                                                 
 conv_pw_8_bn (BatchNormaliz  (None, 14, 14, 512)      2048      
 ation)                                                          
                                                                 
 conv_pw_8_relu (ReLU)       (None, 14, 14, 512)       0         
                                                                 
 conv_dw_9 (DepthwiseConv2D)  (None, 14, 14, 512)      4608      
                                                                 
 conv_dw_9_bn (BatchNormaliz  (None, 14, 14, 512)      2048      
 ation)                                                          
                                                                 
 conv_dw_9_relu (ReLU)       (None, 14, 14, 512)       0         
                                                                 
 conv_pw_9 (Conv2D)          (None, 14, 14, 512)       262144    
                                                                 
 conv_pw_9

In [5]:
def dir_to_category(Categories, datadir):
    flat_data_arr=[] #input array
    target_arr=[] #output array
    for i in Categories:
        print(f'loading... category: {i}')

        path = os.path.join(datadir,i)

        for img in os.listdir(path):

            img_array = load_img(os.path.join(path,img),target_size=(224,224))
            img_array = img_to_array(img_array)
            img_array = np.expand_dims(img_array, axis=0)
            img_array = preprocess_input(img_array)
            img_array = model.predict(img_array)
            flat_data_arr.append(img_array.flatten())
            target_arr.append(Categories.index(i))
        print(f'loaded categoies:{i} successfully')

    flat_data = np.array(flat_data_arr)
    target = np.array(target_arr)
    df = pd.DataFrame(flat_data)

    df['Target'] = target

    x = df.iloc[:,:-1]
    y = df.iloc[:,-1]
    
    return x, y   

In [6]:
np.linspace(1,14,14)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14.])

In [6]:
Categories=[ '1',  '2',  '3',  '4',  '5',  '6',  '7',  '8',  '9', '10', '11', '12', '13','14']
datadir='New' 
import os
x,y  = dir_to_category(Categories,datadir) 

loading... category: 1
1/1 [==============================] - 0s 28ms/step
loaded categoies:1 successfully
loading... category: 2
1/1 [==============================] - 0s 28ms/step


1/1 [==============================] - 0s 27ms/step
loaded categoies:2 successfully
loading... category: 3
1/1 [==============================] - 0s 29ms/step


1/1 [==============================] - 0s 29ms/step
loaded categoies:3 successfully
loading... category: 4
1/1 [==============================] - 0s 29ms/step
loaded categoies:4 successfully
loading... category: 5
1/1 [==============================] - 0s 29ms/step


1/1 [==============================] - 0s 31ms/step
loaded categoies:5 successfully
loading... category: 6
1/1 [==============================] - 0s 33ms/step
loaded categoies:6 successfully
loading... category: 7
1/1 [==============================] - 0s 35ms/step


1/1 [==============================] - 0s 34ms/step
loaded categoies:7 successfully
loading... category: 8
1/1 [==============================] - 0s 31ms/step
loaded categoies:8 successfully
loading... category: 9
1/1 [==============================] - 0s 32ms/step


1/1 [==============================] - 0s 31ms/step
loaded categoies:9 successfully
loading... category: 10
1/1 [==============================] - 0s 31ms/step
loaded categoies:10 successfully
loading... category: 11
1/1 [==============================] - 0s 31ms/step


1/1 [==============================] - 0s 32ms/step
loaded categoies:11 successfully
loading... category: 12
1/1 [==============================] - 0s 32ms/step
loaded categoies:12 successfully
loading... category: 13
1/1 [==============================] - 0s 33ms/step


1/1 [==============================] - 0s 32ms/step
loaded categoies:13 successfully
loading... category: 14
1/1 [==============================] - 0s 31ms/step
loaded categoies:14 successfully


In [7]:
np.save('x.npy',x)
np.save('y.npy',y)

In [8]:
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

In [9]:
# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42,stratify = y )

In [10]:
x.shape, y.shape

((1168, 1000), (1168,))

In [11]:
# Train an SVC classifier on the training data
clf = SVC(kernel='linear', C=1,degree = 5, random_state=42)
clf.fit(X_train, y_train)

# Evaluate the classifier on the test data
score = clf.score(X_test, y_test)
print("Test accuracy: {:.2f}%".format(score * 100))

Test accuracy: 94.87%


In [12]:
# Evaluate the classifier on the test data
y_pred = clf.predict(X_test)
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Classification Report:
               precision    recall  f1-score   support

           0       0.91      1.00      0.95        21
           1       1.00      0.90      0.95        21
           2       0.91      0.95      0.93        21
           3       0.95      0.86      0.90        21
           4       1.00      1.00      1.00        15
           5       0.87      0.93      0.90        14
           6       1.00      0.93      0.97        15
           7       0.94      1.00      0.97        15
           8       1.00      0.87      0.93        15
           9       0.88      0.93      0.90        15
          10       0.94      1.00      0.97        15
          11       0.94      0.94      0.94        16
          12       1.00      1.00      1.00        15
          13       1.00      1.00      1.00        15

    accuracy                           0.95       234
   macro avg       0.95      0.95      0.95       234
weighted avg       0.95      0.95      0.95       234

C

In [14]:
import pickle

# Save the model to disk
filename = 'svc_model.pkl'
pickle.dump(clf, open(filename, 'wb'))


In [15]:
model.save('model.h5')

In [16]:
# Save the function to disk
filename = 'preprocessing.pkl'
with open(filename, 'wb') as f:
    pickle.dump(preprocess_input, f)

# lodaing model and processing

In [39]:

# Load the preprocessing function from disk
filename = 'preprocessing.pkl'
with open(filename, 'rb') as f:
    preprocess_input = pickle.load(f)

In [40]:
import tensorflow as tf
model = tf.keras.models.load_model('model.h5')

In [41]:
# Load the model from disk
filename = 'svc_model.pkl'
clf = pickle.load(open(filename, 'rb'))

In [42]:
from tensorflow.keras.preprocessing.image import array_to_img,img_to_array,load_img 

In [43]:
img_array = load_img(os.path.join('New/1','maithili_2.png'),target_size=(224,224))
img_array = img_to_array(img_array)
img_array = np.expand_dims(img_array, axis=0)
img_array = preprocess_input(img_array)
img_array = model.predict(img_array)
flat_arr = img_array.flatten()
flat_arr

1/1 [==============================] - 0s 381ms/step


array([-1.85546362e+00, -1.13131607e+00, -2.07867265e-01, -1.96643722e+00,
       -6.50406182e-01, -5.05514145e+00, -4.98027563e+00, -2.84575558e+00,
       -7.04251480e+00, -2.65051436e+00,  6.74459696e-01, -2.04488897e+00,
       -2.25821972e+00, -3.67093253e+00, -2.53952599e+00,  1.79346800e-02,
       -6.57874942e-02, -1.62421751e+00, -6.56478405e-02, -2.00133395e+00,
       -2.77731967e+00, -9.46562290e-02, -2.99721432e+00, -3.85980320e+00,
       -8.73771846e-01,  4.20199543e-01,  6.24156892e-01,  1.01240957e+00,
        1.42075121e-02, -4.48218077e-01, -1.43966877e+00, -9.65775967e-01,
       -6.69512510e-01, -1.28640437e+00, -4.62066382e-01, -3.62981319e+00,
       -1.32685554e+00, -9.09885108e-01,  3.03066468e+00, -4.09387302e+00,
       -1.01893508e+00,  8.57334018e-01, -2.72233844e-01,  5.00489771e-01,
       -1.34315217e+00, -1.68629360e+00, -9.48096156e-01, -1.76086903e+00,
       -3.92349029e+00, -3.68076825e+00, -4.21765566e+00, -4.27062893e+00,
       -4.35916305e-01,  

In [44]:
y_clf= clf.predict(flat_arr.reshape(1,-1))

In [45]:
y_clf

array([0])